spring:
  application:
    name: ElasticDataLoader

# logging:
#   level:
#     org.hibernate.SQL: DEBUG
#     org.hibernate.type.descriptor.sql.BasicBinder: TRACE

mysql:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/bank_details
    username: root
    password: MySqlRoot28!
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool-name: HikariPool-MySQL
    maximum-pool-size: 10
    type: com.zaxxer.hikari.HikariDataSource

oracle:
  datasource:
    jdbc-url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: system
    password: OracleSystem28
    driver-class-name: oracle.jdbc.OracleDriver
    pool-name: HikariPool-Oracle
    maximum-pool-size: 10
    type: com.zaxxer.hikari.HikariDataSource
 